package org.schabi.newpipe.extractor.stream;

import java.util.Locale;
import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.exceptions.ParsingException;
import org.schabi.newpipe.extractor.services.youtube.ItagItem;
import org.schabi.newpipe.extractor.utils.LocaleCompat;

public final class SubtitlesStream extends Stream {
    public final MediaFormat k;
    public final Locale l;
    public final boolean m;
    public final String n;

    public static final class Builder {
        public String a;
        public String b;
        public boolean c;
        public DeliveryMethod d = DeliveryMethod.PROGRESSIVE_HTTP;
        public MediaFormat e;
        public String f;
        public String g;
        public Boolean h;

        public SubtitlesStream build() throws ParsingException {
            String str;
            if (this.b == null) {
                throw new IllegalStateException("No valid content was specified. Please specify a valid one with setContent.");
            } else if (this.d == null) {
                throw new IllegalStateException("The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead withsetDeliveryMethod.");
            } else if (this.g == null) {
                throw new IllegalStateException("The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode.");
            } else if (this.h != null) {
                if (this.a == null) {
                    StringBuilder sb = new StringBuilder();
                    sb.append(this.g);
                    if (this.e != null) {
                        str = "." + this.e.g;
                    } else {
                        str = "";
                    }
                    sb.append(str);
                    this.a = sb.toString();
                }
                return new SubtitlesStream(this.a, this.b, this.c, this.e, this.d, this.g, this.h.booleanValue(), this.f);
            } else {
                throw new IllegalStateException("The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated.");
            }
        }

        public Builder setAutoGenerated(boolean z) {
            this.h = Boolean.valueOf(z);
            return this;
        }

        public Builder setContent(String str, boolean z) {
            this.b = str;
            this.c = z;
            return this;
        }

        public Builder setDeliveryMethod(DeliveryMethod deliveryMethod) {
            this.d = deliveryMethod;
            return this;
        }

        public Builder setId(String str) {
            this.a = str;
            return this;
        }

        public Builder setLanguageCode(String str) {
            this.g = str;
            return this;
        }

        public Builder setManifestUrl(String str) {
            this.f = str;
            return this;
        }

        public Builder setMediaFormat(MediaFormat mediaFormat) {
            this.e = mediaFormat;
            return this;
        }
    }

    public SubtitlesStream(String str, String str2, boolean z, MediaFormat mediaFormat, DeliveryMethod deliveryMethod, String str3, boolean z2, String str4) {
        super(str, str2, z, mediaFormat, deliveryMethod, str4);
        this.l = LocaleCompat.forLanguageTag(str3).orElseThrow(new j7(str3, 5));
        this.n = str3;
        this.k = mediaFormat;
        this.m = z2;
    }

    public boolean equalStats(Stream stream) {
        if (super.equalStats(stream) && (stream instanceof SubtitlesStream)) {
            SubtitlesStream subtitlesStream = (SubtitlesStream) stream;
            if (!this.n.equals(subtitlesStream.n) || this.m != subtitlesStream.m) {
                return false;
            }
            return true;
        }
        return false;
    }

    public String getDisplayLanguageName() {
        Locale locale = this.l;
        return locale.getDisplayName(locale);
    }

    public String getExtension() {
        return this.k.g;
    }

    public ItagItem getItagItem() {
        return null;
    }

    public String getLanguageTag() {
        return this.n;
    }

    public Locale getLocale() {
        return this.l;
    }

    public boolean isAutoGenerated() {
        return this.m;
    }
}
